export default [
  {
    id: 1,
    nombre: "Aceite",
    price: 50,
    peso: "5",
    tipo: "primitivo",
    unidad: "lt",
    descripcion: "lorem ipsum esto es una ejmeplo ",
  },
  {
    id: 2,
    nombre: "Pan",
    price: 60,
    peso: "80",
    tipo: "primitivo",
    unidad: "g",
    descripcion: "lorem ipsum esto es una ejmeplo ",
  },
  {
    id: 3,
    nombre: "Pure de Tomate",
    price: 70.5,
    peso: "800",
    tipo: "primitivo",
    unidad: "g",
    descripcion: "lorem ipsum esto es una ejmeplo ",
  },
  {
    id: 4,
    nombre: "Pizza",
    price: 30,
    peso: "300",
    tipo: "Elaborado",
    unidad: "g",
    descripcion: "lorem ipsum esto es una ejmeplo ",
  },

  {
    id: 5,
    nombre: "Queso Gouda",
    price: 30,
    peso: "2",
    tipo: "primitivo",
    unidad: "kg",
    descripcion: "lorem ipsum esto es una ejmeplo ",
  },
];
